### ISSUE TITLE
users with too many gists are getting their comment checks rate limited

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#16]
Got to find some way around this.

**Comment by mottosso** [comment]
I've stumbled upon this issue before, and ended up using my API Token to perform requests, instead of making them anonymously. That should get you out of the way of limits I think.

Here's one Python example of how to achieve it.
- [https://github.com/mottosso/be/blob/master/be/_extern.py#L194](https://github.com/mottosso/be/blob/0f3d4f3597c71223f616d78c6d9b2c8dffcd8a71/be/_extern.py#L194)

**Comment by mattstauffer** [comment]
@mottosso Thanks--we're actually trying to use the token, but somehow still being limited to 60. We'll need to try to dig into why--we had some issues with the PHP SDK that it wasn't passing tokens correctly.

**Comment by mattstauffer** [comment]
@adamwathan If you have any spare time, we're running into the stupid 60-per-hour limit on the comments check I'll be looking at it when i can over the next few days but if you have any time to play with it I'd love it.

Here's a sample error:

```
[2015-11-26 00:00:54] production.INFO: Attempting to queue "get comments" for user 191 after GitHub exception. Delayed exceution for 60 minutes after (5) attempts. Message: [You have reached GitHub hour limit! Actual limit is: 60] Exception class: [Github\Exception\RuntimeException]
```

**Comment by mattstauffer** [comment]
Copied the manual authentication we set up for Gistlog. I think this'll do it.

https://github.com/tightenco/giscus/commit/9356f1a62804244b3749df70046497b28af43fdc

**Comment by mottosso** [comment]
I'll keep an eye out for updates and get back if I notice any that didn't come through. Thanks a lot for taking the time!
